modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/CreateTechified/ReTechified-Mod/issues"
license = "MIT License"
showAsResourcePack = true

[[mods]]
modId = "retechified"
version = "${version}"
displayName = "ReTechified"
authors = "pineapple, wrldmap"
description = '''
Essentially a texture pack bundled as a mod. Various texture updates for Create: Techified.
'''
logoFile = "pack.png"

[[dependencies.retechified]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.retechified]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
