modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "retechified"
version = "${version}"
displayName = "ReTechified"
authors = "Me!"
description = '''
Essentially a texture pack bundled as a mod. Various texture updates for Create: Techified.
'''
#logoFile = ""

[[dependencies.retechified]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.retechified]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
